// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package ekka.srv.api.message;

public final class MessageServiceProto {
  private MessageServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\"I\n\016MessageRequest\022\n\n\002id\030" +
      "\001 \001(\t\022\023\n\013messageType\030\002 \001(\005\022\026\n\016messagePay" +
      "load\030\003 \001(\014\"G\n\014MessageReply\022\n\n\002id\030\001 \001(\t\022\023" +
      "\n\013messageType\030\002 \001(\005\022\026\n\016messagePayload\030\003 " +
      "\001(\0142A\n\016MessageService\022/\n\013SendMessage\022\017.M" +
      "essageRequest\032\r.MessageReply\"\000B-\n\024ekka.s" +
      "rv.api.messageB\023MessageServiceProtoP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageRequest_descriptor,
        new java.lang.String[] { "Id", "MessageType", "MessagePayload", });
    internal_static_MessageReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MessageReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageReply_descriptor,
        new java.lang.String[] { "Id", "MessageType", "MessagePayload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
