// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package ekka.srv.api.message;

public final class MessageServiceProto {
  private MessageServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\"Y\n\016MessageRequest\022\n\n\002id\030" +
      "\001 \001(\t\022\016\n\006remote\030\002 \001(\t\022\023\n\013messageType\030\003 \001" +
      "(\005\022\026\n\016messagePayload\030\004 \001(\014\"W\n\014MessageRep" +
      "ly\022\n\n\002id\030\001 \001(\t\022\016\n\006remote\030\002 \001(\t\022\023\n\013messag" +
      "eType\030\003 \001(\005\022\026\n\016messagePayload\030\004 \001(\0142A\n\016M" +
      "essageService\022/\n\013SendMessage\022\017.MessageRe" +
      "quest\032\r.MessageReply\"\000B-\n\024ekka.srv.api.m" +
      "essageB\023MessageServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageRequest_descriptor,
        new java.lang.String[] { "Id", "Remote", "MessageType", "MessagePayload", });
    internal_static_MessageReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MessageReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageReply_descriptor,
        new java.lang.String[] { "Id", "Remote", "MessageType", "MessagePayload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
